hello_message: "Здравствуйте! Я Mr Steel Rat и пришлю Вам необходимую информацию."
urls:
  vk: "https://vk.com/mrsteelrat"
  telegram: "https://t.me/MrSteelRat"
  github: "https://github.com/MrSteelRat"
  boosty: "https://boosty.to/mrsteelrat"
  donat_alert: "https://www.donationalerts.com/r/mrsteelrat"